version: "3.9"

services:
  await-helper:
    image: ${AWAIT_HELPER_IMAGE}
    deploy:
      replicas: 1
      restart_policy:
        condition: none
    command: "-k https://openhim-core:8080/heartbeat"
